/*
 * sumobot_defines.h
 *
 *  Created on: 20Jul.,2018
 *      Author: cdk
 */

#ifndef SUMOBOT_DEFINES_H_
#define SUMOBOT_DEFINES_H_

//Defines for laser sensors
#define LASLEFTFRONT_I2C_ADDRESS 0x65
#define LASLEFTREAR_I2C_ADDRESS 0x66
#define LASRIGHTFRONT_I2C_ADDRESS 0x67
#define LASRIGHTREAR_I2C_ADDRESS 0x68
#define LASFRONTLEFT_I2C_ADDRESS 0x69
#define LASFRONTRIGHT_I2C_ADDRESS 0x70
#define LASREARLEFT_I2C_ADDRESS 0x71
#define LASREARRIGHT_I2C_ADDRESS 0x72

#define LASER_SENSOR_TIMING_BUDGET_US 100000
#define LASER_SENSOR_MEASUREMENT_PERIOD_MS 150

//Defines for edge sensors


//Defines for motors
#define LEFT_MOTOR_OCMODE TIM_OCMODE_PWM1;
#define LEFT_MOTOR_PULSE_START 100;
#define LEFT_MOTOR_OCPOLARITY TIM_OCPOLARITY_HIGH;
#define LEFT_MOTOR_OCFAST TIM_OCFAST_DISABLE;
#define LEFT_MOTOR_ENCODER_CPR 1200;

#define RIGHT_MOTOR_OCMODE TIM_OCMODE_PWM1;
#define RIGHT_MOTOR_PULSE_START 100;
#define RIGHT_MOTOR_OCPOLARITY TIM_OCPOLARITY_HIGH;
#define RIGHT_MOTOR_OCFAST TIM_OCFAST_DISABLE;
#define RIGHT_MOTOR_ENCODER_CPR 1200;

#define MIN_PULSE_PWM 0;
#define MAX_PULSE_PWM 16000;



#endif /* SUMOBOT_DEFINES_H_ */
